// ATLProjectDLLFoo.idl : IDL source for ATLProjectDLLFoo
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLProjectDLLFoo.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(0535e1b4-a566-403d-905a-dad5863cdafb),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ICalculator : IDispatch
{
};
[
	uuid(99ca2513-6901-43c3-88d7-cba9b4d17a8f),
	version(1.0),
]
library ATLProjectDLLFooLib
{
	importlib("stdole2.tlb");
	[
		uuid(aba7fe24-4d6d-4290-b8e3-7449b120d560)
	]
	coclass Calculator
	{
		[default] interface ICalculator;
	};
};

import "shobjidl.idl";
