/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Library library = new Library();
        String traceId = library.mainFunction();

        System.out.println("Trace ID is " + traceId);
        System.out.println(new App().getGreeting());
    }
}
